# Generated by Django 5.0.1 on 2024-06-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='Normal', max_length=40),
            preserve_default=False,
        ),
    ]
