# Generated by Django 4.1.13 on 2024-06-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('EXPERT', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.experts')),
            ],
        ),
        migrations.CreateModel(
            name='E_Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=400)),
                ('EXPERT', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.experts')),
            ],
        ),
    ]
