# Generated by Django 3.2.24 on 2024-06-28 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_e_feedback_e_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('EXPERT', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.experts')),
                ('USER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
